# Metadata
title: "SEAMUS 2020 Digital Conference"
description: "The digital home for the 2020 Conference of the Society for Electroacoustic Musicians in the United States"
keywords: ["electroacoustic", "music", "electronic", "composition"]

# Third party services
# (Anything you put here will be public!)
google-analytics: 

# Build settings
encoding: utf-8
markdown: kramdown
exclude:
  - .sass-cache/
  - node_modules/
  - .gitignore
  - Gemfile
  - _config.yml
  - glitch.json
  - package.json
  - package-lock.json
  - watch.json
  - "*.save.*"